### ISSUE TITLE
Edit event

### ISSUE THREAD

**Issue by carpad88** [carpad88/ohyez#10]
## Description

A user can edit event an event.

## Tasks

- [ ] User can edit event main details
- [ ] User can edit event sections details
- [ ] User can customize template design
- [ ] User can manage invitations
